version: '3.1'

services:

  rs-mongo:
    image: mongo
    command: [ "--bind_ip", "0.0.0.0", "--replSet", "rs0", "--keyFile", "/mng/keyfile.key", "--port", "27048" ]
    restart: always
    env_file: .env
    container_name: users-rs-mongo
    volumes:
      - "./mongodb/replica-set.key:/mng/keyfile.key"
    hostname: localhost
    ports:
      - "27048:27048"
